### ISSUE TITLE
svg image export removes arrows

### ISSUE THREAD

**Issue by salkz** [pleak-tools/pleak-frontend#1]
The svg image export gives out an svg file of the model, but all arrows-heads are removed so that there are only lines representing various flows.

Reported by: [PuellaQuasiDraco](https://github.com/PuellaQuasiDraco)

**Comment by michaeldorokhov** [comment]
Hi! Can you clarify what is an "arrow-head"? Some example would be also nice to have.

**Comment by PuellaQuasiDraco** [comment]
By arrow-head I mean the thing in the end that shows the direction.

However, it now seems that the issue may be with my viewer and not the exporint because if I open the .svg in a browser then I actually can see the arrows properly.

**Comment by salkz** [comment]
Seems to be resolved. Closing.
