### ISSUE TITLE
User was prompted to log in in modeler view but he had logged in before in the initial view

### ISSUE THREAD

**Issue by salkz** [pleak-tools/pleak-frontend#2]
Maybe tokens are saved and parsed differently? Might be a bug or a happy little accident by user.

**Comment by mjoemets** [comment]
Not sure what happened to that user, but that auth logic needs to be changed a bit.
If auth is done, then getFile() should be executed only if file is not already open.
Otherwise recent changes might be lost.

**Comment by salkz** [comment]
Fixed the getFile() part but no clue about the user logging out part.

**Comment by mjoemets** [comment]
Could not reproduce the login prompt on dev.
